apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-example
  namespace: exam
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
